# Generated by Django 4.1.7 on 2023-03-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value_type', models.CharField(choices=[('DR', 'Dollar Amount'), ('PC', 'Percentage')], max_length=100, verbose_name='Type')),
                ('value_num', models.FloatField()),
                ('category', models.ForeignKey(on_delete=models.SET('Category Deleted'), to='budget.category')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.plan')),
            ],
        ),
    ]
